### ISSUE TITLE
How to use sourcecode?

### ISSUE THREAD

**Issue by drpatrikking** [GreatZardasht/Client-Source-Code-Collection#6]
Can i play on the clients with sourcecode or i need to download .exe/.jar files?

**Comment by Ali00035v2** [comment]
You have to compile it to use

**Comment by drpatrikking** [comment]
> 

And how to compile?

**Comment by andrewbelling** [comment]
> > 
> 
> And how to compile?

How to compile Java:
1. stop being dumb
2. Download Eclipse IDE
3. get MCP
4. put sources in mcp
5. open in eclipse
6. compile

**Comment by drpatrikking** [comment]
The first step is so hard

**Comment by ghost** [comment]
Follow this tutorial:
https://www.youtube.com/watch?v=XdPI4UF92kg
Then, copy paste any client's source you want into src > minecraft folder
Hope I helped you unlike others! :)
